# https://docs.netlify.com/configure-builds/file-based-configuration

[build]
  environment = { PYTHON_VERSION = "3.13", MISE_IDIOMATIC_VERSION_FILE_ENABLE_TOOLS = "[]" }
  base    = "docs/"
  publish = "site/"
  command = "make build"
