site_name: LSP for Sublime Text
site_url: https://sublimelsp.github.io/LSP/
repo_url: https://github.com/sublimelsp/LSP/
edit_uri: edit/main/docs/src/
docs_dir: 'src'
use_directory_urls: false

plugins:
  - search
  - redirects:
      redirect_maps:
        'guides/cplusplus.md': 'https://github.com/sublimelsp/LSP-clangd'
        'guides/client_configuration.md': 'client_configuration.md'

theme:
  name: material
  palette:
    scheme: slate
    accent: orange
    primary: orange
  logo: images/logo.svg
  favicon: images/favicon.svg
  features:
    - content.code.copy
    - content.tooltips
    - navigation.top

# override css
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/redirect.js

markdown_extensions:
  # tabs for ST4 and ST3 content
  - pymdownx.tabbed

  # highlight code blocks
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: jsonc
          lang: json
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # add tip, warning info boxes
  - admonition

  - md_in_html

  # show # after each header
  - toc:
      permalink: '#'

nav:
  - Getting Started: index.md
  - Language Servers: language_servers.md
  - Features: features.md
  - Commands: commands.md
  - Keyboard Shortcuts: keyboard_shortcuts.md
  - Customization: customization.md
  - Client Configuration: client_configuration.md
  - Troubleshooting: troubleshooting.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TZ5WN8t
